{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    {{- include "app.labels" . | indent 4 }}
spec:
  dataFrom:
    - extract:
        conversionStrategy: Default
        decodingStrategy: None
        key: {{ default (include "app.fullname" .) .Values.externalSecrets.key  }}
  refreshInterval: 60s
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-backend
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ template "app.fullname" . }}
{{- end }}